version: "3"
services:
  react-app:
    container_name: react-app
    image: react-app:latest  # <- Agrega esta línea
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 80:3000
    volumes:
      - /app/node_modules
      - ./:/app

