version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run: echo 'export NODE_OPTIONS=--openssl-legacy-provider' >> $BASH_ENV
      - run: npm install
      - run: npm run build

